spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=GMT%2B8
    username: root
    password: 2673253736Cxr
  redis:
    port: 6379
    host: 192.168.44.3
    client-type: lettuce
mybatis-plus:
  type-aliases-package: com.xzit.gene.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:com/xzit/gene/mapper/*.xml